// <auto-generated />
namespace db.timesheet.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ActivityDepartmentMappingone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActivityDepartmentMappingone));
        
        string IMigrationMetadata.Id
        {
            get { return "202103101554130_Activity-Department Mapping one"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
