// <auto-generated />
namespace db.timesheet.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class renamingcolname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamingcolname));
        
        string IMigrationMetadata.Id
        {
            get { return "202103121423373_renaming col name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
