// <auto-generated />
namespace db.timesheet.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class timesheetandaccounttablemapping2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(timesheetandaccounttablemapping2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103120430585_timesheet and account table mapping 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
